# coding : utf-8
'''
Created on 15.04.2013

@author: Igor
'''

import dals.os_io.io_wrapper as dal

def printer(msg):
    print msg

if __name__=='__main__':
    sets = dal.get_utf8_template()
    path = 'D:/home/lugansky-igor/tmitter-web-service-win/server_side_code/top_service/'
    fname = path+'copy_top_service_ajax_set_sets.cc'
    sets['name'] = fname

    result = []
    content = dal.file2list(sets)
    insert_in_next_line = False
    for at in content:
        if 'p["' in at and '!=' in at:
            result.append( at+' \n// STR_PARAM [Autogenerated]:\n    string msg = "Change_to :"+p["'+at.split('"')[1]+'"];')
            result.append( '    sampler_.journal.PutRecord(msg);')
            result.append( '    GSNMPJournal->SendWarning(msg, kSnmpOk);')
            result.append( '// Autogenerated\n')
        elif 'itmp = a' in at:
            result.append( at )
            insert_in_next_line = True
        else:
            if insert_in_next_line:
                result.append( at+' \n// INT_PARAM [Autogenerated]:\n string msg = "Change_to: "+to_string('+"itmp"+");")
                result.append( '    sampler_.journal.PutRecord(msg);')
                result.append( '    GSNMPJournal->SendWarning(msg, kSnmpOk);')
                result.append( '// Autogenerated\n')
                insert_in_next_line = False
            else:
                result.append( at )
        
        
    map(printer, result)
    
    sets['howOpen'] = 'w'
    sets['name'] = path+'ajax_set_settings_at.cc'
    sets['coding'] = 'cp1251'
    dal.list2file(sets, result)