; #include <../headers/info.inc>

; Danger!!
	global 	CurrentUm
	global	Vremen
	;g lobal  Resp_UM2		;+andr	  ;// _BUM
; Danger!!

constant	HERE = 3
#define		_v3_INFO	_v3_INFO
#define		THIS	_v3_INFO
#include	<../headers/user_modes.inc>
;// только здесь подключаем заголовочный файл
#include 	<../headers/math/math_wrapper.inc>
#include	<../headers/engine/_v3_INFO.inc>
#include	<../headers/fixed/init_data.inc>

constant	LOGNUMBER=62
#define L 'L'
#define H 'H'

